import sendEmail from "../transporter";
import { Head, Hr, Html, Img, Link, Preview, Section, Text, Row, Column, render } from "@react-email/components";

export function SchoolReceiveReceipt({ officialName, schoolName }) {
	return (
		<Row>
			<Column>
				<Text className="mt-0 text-[15px]">
					Dear {officialName},
					<br />
					<br />
					Your school, {schoolName}, has received a receipt. Please visit the Invoices section on MediBook to view the receipt.
					<br />
					<br />
					If you have any questions or need assistance, please feel free to contact us.
					<br />
					<br />
					<span className="text-xs">
						Please note that receipts generated by MEDIMUN are for reference purposes only and do not serve as official receipts.
					</span>
				</Text>
			</Column>
		</Row>
	);
}
