import sendEmail from "../transporter";
import { Head, Hr, Html, Img, Link, Preview, Section, Text, Row, Column, render } from "@react-email/components";

export function UserReceiveInvoice({ officialName }) {
	return (
		<Row>
			<Column>
				<Text className="mt-0 text-[15px]">
					Dear {officialName},
					<br />
					<br />
					Your have received an invoice. Please visit the Invoices section on MediBook to view and pay the invoice.
					<br />
					<br />
					If you have any questions or need assistance, please feel free to contact us.
					<br />
					<br />
					<span className="text-xs">
						Please note that invoices generated by MEDIMUN are for reference purposes only and do not serve as official invoices.
					</span>
				</Text>
			</Column>
		</Row>
	);
}
