export default async function Page() {
	return (
		<div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
			<div>hi</div>
		</div>
	);
}
